package com.techtalentsouth.TechTalentBlog;



import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.validation.constraints.NotBlank;
import javax.validation.constraints.Size;

import org.hibernate.annotations.Type;

@Entity
public class BlogPost {

	@Id  //id as primary key
	@GeneratedValue(strategy=GenerationType.AUTO) //allows id to be generated by underlying database
	private Long id; 
	
	@Size(max=255)
    private String title;
	
	@Size(max=255)
	private String author;
	
	@Type(type="text")
	private String blogEntry;
	
	public BlogPost() {
		//no argument constructor needed for jpa
	}
	
	public BlogPost(Long id, String title, String author, String blogEntry) {
		this.id = id;
		this.title = title; 
		this.author = author;
		this.blogEntry = blogEntry;
	}


	public Long getId() {
		return id;
	}


	public void setId(Long id) {
		this.id = id;
	}


	public String getTitle() {
		return title;
	}


	public void setTitle(String title) {
		this.title = title;
	}


	public String getAuthor() {
		return author;
	}


	public void setAuthor(String author) {
		this.author = author;
	}


	public String getBlogEntry() {
		return blogEntry;
	}


	public void setBlogEntry(String blogEntry) {
		this.blogEntry = blogEntry;
	}


	@Override
	public String toString() {
		return "BlogPost [title=" + title + ", author=" + author + ", blogEntry=" + blogEntry + "]";
	}
	
	
}
