package com.techtalentsouth.TechTalentBlog;



import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;

@Entity
public class BlogPost {

	@Id  //id as primary key
	@GeneratedValue(strategy=GenerationType.AUTO) //allows id to be generated by underlying database
	private Long id; 
    private String title;
	private String author;
	private String blogEntry;
	
	public BlogPost() {
		//no argument constructor needed for jpa
	}
	
	public BlogPost(String title, String author, String blogEntry) {
		this.title = title; 
		this.author = author;
		this.blogEntry = blogEntry;
	}


	public Long getId() {
		return id;
	}


	public void setId(Long id) {
		this.id = id;
	}


	public String getTitle() {
		return title;
	}


	public void setTitle(String title) {
		this.title = title;
	}


	public String getAuthor() {
		return author;
	}


	public void setAuthor(String author) {
		this.author = author;
	}


	public String getBlogEntry() {
		return blogEntry;
	}


	public void setBlogEntry(String blogEntry) {
		this.blogEntry = blogEntry;
	}


	@Override
	public String toString() {
		return "BlogPost [id=" + id + ", title=" + title + ", author=" + author + ", blogEntry=" + blogEntry + "]";
	}
	
	
}
